# Generated by Django 4.2 on 2023-05-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_postcomment_post_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='content',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
