# Generated by Django 4.2 on 2023-08-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_postcomment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reports',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='post_pics/'),
        ),
    ]
