# Generated by Django 4.2 on 2023-07-19 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_followers_profile_timestamp_profile_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='nickname',
            new_name='location',
        ),
    ]
